DesignStamp/Models/DetailView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DesignStamp.Models
{
    public class DetailView
    {

        [Display(Name = "№ детали")]
        public string Name { get; set; }
        [Display(Name = "№ штампа")]
        public string StampName { get; set; }

    }
}

DesignStamp/Models/StampView.cs
using DataLayer.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DesignStamp.Models
{
    public class StampView
    {
        [Display(Name = "№ штампа")]
        public string Name { get; set; }
        [Display(Name = "№ детали")]
        public string NameDetail { get; set; }
        [Display(Name = "Закрытая высота")]
        public int ClosedHeight { get; set; }
        [Display(Name = "Масса")]
        public double Weight { get; set; }
        public AllForceView AllForce { get; set; }
        public HolderView Holder { get; set; }
        public MatrixView Matrix { get; set; }
        public PullerView Puller { get; set; }
        public PunchMatrixView PunchMatrix { get; set; }
        public SpringView Spring { get; set; }
        public BottomPlateView BottomPlate { get; set; }
        public TopPlateView TopPlate { get; set; }
        public BushingView Bushing { get; set; }
        public ColumnView Column { get; set; }
        public CoverView Cover { get; set; }
        public List<PunchView> Punches { get; set; }
        public List<EnlargedPunchView> EnlargedPunches { get; set; }
        public PressView Press { get; set; }
        


    }
}

DesignStamp/Areas/Identity/Pages/Account/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataLayer.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace DesignStamp.Areas.Identity.Pages.Account
{
    public class EditModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<EditModel> _logger;

        public EditModel(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            ILogger<EditModel> logger)

        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;

        }
        [BindProperty]
        public ApplicationUser User1 { get; set; }
        public async Task<IActionResult> OnGetAsync( string name)
        {
            //ReturnUrl = returnUrl;

            User1 =await _userManager.FindByNameAsync(name);
            return Page();
            
        }
    }
}

DesignStamp/Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataLayer.Data;
using DataLayer.Entities;
using BuissnesLayer;
using DesignStamp.Models;
using Microsoft.AspNetCore.Authorization;

namespace DesignStamp.Controllers
{
    [Authorize]
    public class DetailsController : Controller
    {
        readonly private DataManager _dataManager;
        readonly private ServicesManager _servicesManager;

        public DetailsController(DataManager dataManager)
        {

            _dataManager = dataManager;
            _servicesManager = new ServicesManager(_dataManager);
        }

        // GET: DetailsView
        public IActionResult GetAllDetails(string name)
        {
            List<Detail> details = _dataManager.Details.GetAllDetail();
            if (details.Count() == 0)
                ViewData["Flag"] = 1;
            else
                ViewData["Flag"] = 0;


            List<DetailView> detailViews=new List<DetailView>();
            foreach (var item in details)
            {
                var stamp = _dataManager.Stamps.GetStampByDetailName(item.Name);
                string StampName = stamp?.Name ?? "Нету штампа";
                detailViews.Add(new DetailView { Name = item.Name, StampName = StampName });
            }

            if (name != null)
                detailViews= detailViews.Where(s => s.Name == name).ToList();


            return View(detailViews);
        }

        // GET: DetailsView/DetailsView/5
        public IActionResult Details(string name, string returnUrl)
        {
            ViewData["Url"] = returnUrl;
            if (name == null)
            {
                return NotFound();
            }

            var detail = _dataManager.Details.GetDetailByName(name,true);

            if (detail == null)
            {
                return NotFound();
            }

            return View(detail);
        }


        // POST: DetailsView/Delete/5
       
        public IActionResult Delete(string name, string returnUrl)
        {
            ViewData["Url"] = returnUrl;
            var detail = _dataManager.Details.GetDetailByName(name,true);
            return View(detail);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(string Name)
        {
            var stamp = _dataManager.Stamps.GetStampByDetailName(Name);
            if (stamp != null)
                _dataManager.Stamps.DeleteStamp(stamp.Name);
            var detail = _dataManager.Details.GetDetailByName(Name, true);
            _dataManager.Details.DeleteDetail(detail);
            //return RedirectToAction(nameof(GetAllDetails));

            return View();

        }

        [AcceptVerbs("Get", "Post")]
        public IActionResult CheckDetail (string Name)
        {
            var detail = _dataManager.Details.GetDetailByName(Name);
            if (detail == null)
                return Json(true);
            return Json(false);
        }
    }
}

DesignStamp/Controllers/StampsController.cs
using BuissnesLayer;
using DataLayer.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DesignStamp.Controllers
{
    [Authorize]
    public class StampsController : Controller
    {
        private DataManager _datamanager;
        private ServicesManager _servicesManager;
        public StampsController(DataManager dataManager)
        {

            _datamanager = dataManager;
            _servicesManager = new ServicesManager(_datamanager);
        }

        public IActionResult GetAllStamps(string stampName=null)
        {
        //    if (details.Count() == 0)
        //        ViewData["Flag"] = 1;
        //    else
                
            List<Stamp> stamps;
            ViewData["Flag"] = 2;
            if (stampName == null)
            {
                stamps = _datamanager.Stamps.GetAllStamp();
                if(stamps.Count()==0)
                    ViewData["Flag"] = 0;
            }
                
            else
            {
                stamps = _datamanager.Stamps.GetAllStamp().Where(s => s.Name == stampName).ToList();
                if(stamps.Count() == 0)
                ViewData["Flag"] = 1;
            }
               

            return View(stamps);
        }

        public IActionResult GetStamp(string stampName, string returnUrl)
        {
            ViewData["Url"] = returnUrl;
            var stamp = _servicesManager.Stamps.GetViewStampByName(stampName);

            return View(stamp);
        }

        public IActionResult DeleteStamp(string stampName, string returnUrl)
        {
            ViewData["Url"] = returnUrl;
            if (stampName == null)
            {
                return NotFound();
            }

            var stamp=_datamanager.Stamps.GetStampByName(stampName,true);
            

            return View(stamp);
           

            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(string Name)
        {
            _datamanager.Stamps.DeleteStamp(Name);

            return View();

        }



        public IActionResult EditColumn(int id, int oldId)
        {
            _servicesManager.Stamps.SaveStampColumnToDb(id, oldId);
            return RedirectToAction(nameof(GetStamp), new { @stampName = _datamanager.Stamps.GetStampByColumnId(id).Name });
        }

        public IActionResult EditBushing(int id, int oldId)
        {
            _servicesManager.Stamps.SaveStampBushingToDb(id, oldId);
            return RedirectToAction(nameof(GetStamp), new { @stampName = _datamanager.Stamps.GetStampByBushingId(id).Name });
        }

        public IActionResult EditCover(int id, int oldId)
        {
            _servicesManager.Stamps.SaveStampCoverToDb(id, oldId);
            return RedirectToAction(nameof(GetStamp), new { @stampName = _datamanager.Stamps.GetStampByCoverId(id).Name });
        }

        public IActionResult EditPunch(int id, int oldId)
        {
            _servicesManager.Stamps.SaveStampPunchToDb(id, oldId);
            return RedirectToAction(nameof(GetStamp), new { @stampName = _datamanager.Stamps.GetStampByPunchId(id).Name });
        }

        public IActionResult EditSpring(int id, int oldId)
        {
            _servicesManager.Stamps.SaveStampSpringToDb(id, oldId);
            return RedirectToAction(nameof(GetStamp), new { @stampName = _datamanager.Stamps.GetStampBySpringId(id).Name });
        }

        public IActionResult EditEnlargedPunch(int id, int oldId)
        {
            _servicesManager.Stamps.SaveStampEnlargedPunchToDb(id, oldId);
            return RedirectToAction(nameof(GetStamp), new { @stampName = _datamanager.Stamps.GetStampByEnlargedPunchId(id).Name });
        }

        public IActionResult EditPress(int id, int oldId)
        {
            _servicesManager.Stamps.SaveStampPressToDb(id, oldId);
            return RedirectToAction(nameof(GetStamp), new { @stampName = _datamanager.Stamps.GetStampByPressId(id).Name });
        }


        public IActionResult GetAllForce(string stampName )
        {
            var force = _servicesManager.AllForces.GetAllForceViewByStampName(stampName);

            return View(force);
        }
        [AcceptVerbs("Get", "Post")]
    public IActionResult CheckStamp(string stampName)
        {
            var stamp = _datamanager.Stamps.GetStampByName(stampName);
            if (stamp == null)
                return Json(true);
            return Json(false);
        }
    }
}

DesignStamp/Views/Stamps/Create.cshtml
@model DataLayer.Entities.Stamp

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Stamp</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="detailName" class="control-label"></label>
                <select asp-for="detailName" class ="form-control" asp-items="ViewBag.detailName"></select>
            </div>
            <div class="form-group">
                <label asp-for="BushingId" class="control-label"></label>
                <select asp-for="BushingId" class ="form-control" asp-items="ViewBag.BushingId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ColumnId" class="control-label"></label>
                <select asp-for="ColumnId" class ="form-control" asp-items="ViewBag.ColumnId"></select>
            </div>
            <div class="form-group">
                <label asp-for="SpringId" class="control-label"></label>
                <select asp-for="SpringId" class ="form-control" asp-items="ViewBag.SpringId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DesignStamp/Views/Stamps/DeleteConfirmed.cshtml
@model DataLayer.Entities.Stamp

@{
    ViewData["Title"] = "Delete";
}



<h2>Штамп успешно удален!</h2>
<br/>
<br/>
<div class="row">

    <a class="col-md-2  offset-md-4 btn btn-secondary" asp-controller="Stamps" asp-action="GetAllStamps" > OK </a>

</div>

DesignStamp/Views/Stamps/DeleteStamp.cshtml
@model DataLayer.Entities.Stamp

@{
    ViewData["Title"] = "DeleteStamp";
    string url = (string)ViewData["Url"] ?? "#";
}

<h1>Удаление</h1>

<h3>Вы действительно хотите удалить штамп?</h3>
<div>
    <h4>Штамп</h4>
    <hr />


    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.detailName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.detailName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ClosedHeight)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ClosedHeight)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.press.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.press.Name)
        </dd>
    </dl>

    <form asp-action="DeleteConfirmed" asp-controller="Stamps">
        <input type="hidden" asp-for="Name" />
        <input type="submit" value="Удаление" class="btn btn-danger" />
        <br />
        <br />
        <a class="btn btn-secondary" href="@url">Назад </a>
    </form>
</div>
@*<a href="@url" class="col-md-3 offset-md-4 btn btn-secondary">
    Назад
</a>*@

DesignStamp/Views/Stamps/Details.cshtml
@model DataLayer.Entities.Stamp

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Stamp</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.detail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.detail.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.bushing)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.bushing.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.column)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.column.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.spring)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.spring.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Name">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DesignStamp/Views/Stamps/Edit.cshtml
@model DataLayer.Entities.Stamp

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Stamp</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Name" />
            <div class="form-group">
                <label asp-for="detailName" class="control-label"></label>
                <select asp-for="detailName" class="form-control" asp-items="ViewBag.detailName"></select>
                <span asp-validation-for="detailName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BushingId" class="control-label"></label>
                <select asp-for="BushingId" class="form-control" asp-items="ViewBag.BushingId"></select>
                <span asp-validation-for="BushingId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ColumnId" class="control-label"></label>
                <select asp-for="ColumnId" class="form-control" asp-items="ViewBag.ColumnId"></select>
                <span asp-validation-for="ColumnId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SpringId" class="control-label"></label>
                <select asp-for="SpringId" class="form-control" asp-items="ViewBag.SpringId"></select>
                <span asp-validation-for="SpringId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DesignStamp/Views/Stamps/GetAllForce.cshtml
@model AllForceView
<h3>Усилия</h3>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Pfelling)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ppunching)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ptotal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ppress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Qremoval)
            </th>
            
        </tr>
    </thead>
    <tbody>


        <tr>
            <td>
                @Html.DisplayFor(model => model.Pfelling)
            </td>
            <td>
                @Html.DisplayFor(model => model.Ppunching)
            </td>
            <td>
                @Html.DisplayFor(model => model.Ptotal)
            </td>
            <td>
                @Html.DisplayFor(model => model.Ppress)
            </td>
            <td>
                @Html.DisplayFor(model => model.Qremoval)
            </td>
            
           
        </tr>

    </tbody>
</table>
<div class="row">

    <a class="col-md-4 offset-md-4 btn btn-secondary" asp-controller="Stamps" asp-action="GetStamp" asp-route-stampName="@Model.StampName"> Вернутся к штампу</a>

</div>

DesignStamp/Views/Stamps/GetAllStamps.cshtml
@model IEnumerable<DataLayer.Entities.Stamp>

@{
    ViewData["Title"] = "GetAllStamp";
    int Flag = (int)ViewData["Flag"];
}

<h2>Все штампы</h2>

<form  asp-controller="Stamps" asp-action="GetAllStamps">
    <div class="form-group row">
        <div class="col-md-3">
            <input class="form-control me-2 " type="search" name="StampName" placeholder="Введите № штампа" aria-label="Search">
        </div>
        <div class="col-md-6">
            <button class="btn btn-outline-success " type="submit">Поиск</button>
        </div>
     </div>
</form>
@if(Model.Count()!=0)
{ 

    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.press.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ClosedHeight)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.detailName)
                </th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.press.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ClosedHeight)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.detailName)
                    </td>

                    <td>
                        @{ // Получение текущего адреса
                            var request = ViewContext.HttpContext.Request;
                            var returnUrl = request.Path + request.QueryString.ToUriComponent();

                        }
                        <a class="btn btn-outline-success" asp-controller="Stamps" asp-action="GetStamp" asp-route-stampName="@item.Name" asp-route-returnUrl="@returnUrl"><span class="fas fa-info"></span></a>
                        <span>&nbsp</span>
                        <a class="btn btn-outline-danger" asp-action="DeleteStamp" asp-route-stampName="@item.Name" asp-route-returnUrl="@returnUrl"> <span class="fas fa-trash-alt"></span></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
 }
       else if(Flag==0)
       {
        <h3>Нету ни одного рассчитанного штампа</h3>
       }
       else if(Flag==1)
       {
        <h3>Штамп с таким номером не найден</h3>
       }

DesignStamp/Views/Stamps/GetStamp.cshtml
@model StampView

@{
    ViewData["Title"] = "GetStamp";
    string url = (string)ViewData["Url"] ?? "#";
}



<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ClosedHeight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Weight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NameDetail)
            </th>

            <th>

            </th>

        </tr>
    </thead>
    <tbody>


        <tr>
            <td>
                @Html.DisplayFor(model => model.Name)
            </td>
            <td>
                @Html.DisplayFor(model => model.ClosedHeight)
            </td>
            <td>
                @Html.DisplayFor(model => model.Weight)
            </td>
            <td>

                @{ // Получение текущего адреса
                    var request = ViewContext.HttpContext.Request;
                    var returnUrl = request.Path + request.QueryString.ToUriComponent();

                }
                @Html.DisplayFor(model => model.NameDetail)
                <a class="btn btn-outline-success" asp-controller="Details" asp-action="Details" asp-route-name="@Model.NameDetail" asp-route-returnUrl="@returnUrl"><span class="fas fa-info"></span></a>
            </td>
            <td>
                <a class="btn btn-danger" asp-controller="Stamps" asp-action="DeleteStamp" asp-route-stampName="@Model.Name" asp-route-returnUrl="@returnUrl">Удалить штамп</a>
            </td>

        </tr>

    </tbody>
</table>

<partial name="_AllForecePartial" model="Model.AllForce" />
<partial name="_MatrixPartial" model="Model.Matrix" />

<partial name="_HolderPartial" model="Model.Holder" />
<partial name="_PunchMatrixPartial" model="Model.PunchMatrix" />

<partial name="_PullerPartial" model="Model.Puller" />

<partial name="_BottomPlatePartial" model="Model.BottomPlate" />

<partial name="_TopPlatePartial" model="Model.TopPlate" />

<partial name="_ColumnPartial" model="Model.Column" />
<partial name="_BushingPartial" model="Model.Bushing" />
<partial name="_CoverPartial" model="Model.Cover" />
<partial name="_SpringPartial" model="Model.Spring" />
<partial name="_PaunchListPartial" model="Model.Punches" />
<partial name="_EnlargedPaunchListPartial" model="Model.EnlargedPunches" />
<partial name="_PressPartial" model="Model.Press" />

<div class="row">

    @*<a class="col-md-4 offset-md-4 btn btn-secondary" asp-controller="Stamps" asp-action="GetStamp" asp-route-stampName="@Model."> Вернутся к штампу</a>*@
    <a href="@url" class="col-md-3 offset-md-4 btn btn-secondary">
        Назад
    </a>

</div>

DesignStamp/Views/Stamps/Index.cshtml
@model IEnumerable<DataLayer.Entities.Stamp>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.detail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.bushing)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.column)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.spring)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.detail.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.bushing.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.column.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.spring.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Name">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Name">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Name">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>