DesignStamp/Models/BushingView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DesignStamp.Models
{
    public class BushingView
    {
        public int Id { get; set; }
        [Display(Name = "№ втулки")]
        public string Name { get; set; }
        [Display(Name = "Диаметр внедрения (мм)")]
        public int PressedDiametr { get; set; }
        [Display(Name = "Диаметр фланца  (мм)")]
        public int FlangeDiametr { get; set; }
        [Display(Name = "Диаметр колонки  (мм)")]
        public int ColumnDiametr { get; set; }
        [Display(Name = "Высота  (мм)")]
        public int TotalHeight { get; set; }
        [Display(Name = "Высота внедрения (мм)")]
        public int DepthHeight { get; set; }
        [Display(Name = "Кол-во втулок ")]
        public int AmountBushing { get; set; }
        [Display(Name = "Масса (кг) ")]
        public double Weight { get; set; }
    }
}

DesignStamp/Models/DetailView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DesignStamp.Models
{
    public class DetailView
    {

        [Display(Name = "№ детали")]
        public string Name { get; set; }
        [Display(Name = "№ штампа")]
        public string StampName { get; set; }

    }
}

DesignStamp/Areas/Identity/Pages/Account/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataLayer.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace DesignStamp.Areas.Identity.Pages.Account
{
    public class EditModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<EditModel> _logger;

        public EditModel(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            ILogger<EditModel> logger)

        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;

        }
        [BindProperty]
        public ApplicationUser User1 { get; set; }
        public async Task<IActionResult> OnGetAsync( string name)
        {
            //ReturnUrl = returnUrl;

            User1 =await _userManager.FindByNameAsync(name);
            return Page();
            
        }
    }
}

DesignStamp/Controllers/BushingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataLayer.Data;
using DataLayer.Entities;
using BuissnesLayer;
using DesignStamp.Models;
using Microsoft.AspNetCore.Authorization;

namespace DesignStamp.Controllers
{
    [Authorize]
    public class BushingsController : Controller
    {
        readonly private DataManager _dataManager;
        readonly private ServicesManager _servicesManager;

        public BushingsController(DataManager dataManager)
        {

            _dataManager = dataManager;
            _servicesManager = new ServicesManager(_dataManager);
        }

        // GET: Bushings
        public IActionResult ChooseBushing(int diametr, int oldId, string url)
        {
            var listBushing = _dataManager.Bushings.GetBushingsByDiametr(diametr);

            var groupBushing = _dataManager.Bushings.GetAllBushing().GroupBy(d => d.ColumnDiametr);
            List<DropVIew> bushingDrops = new List<DropVIew>();

            foreach (var item in groupBushing)
            {
                bushingDrops.Add(new DropVIew { Diametr = item.Key, OldId = oldId, Url = url });
            }


            ViewData["Drops"] = bushingDrops;
            ViewData["Current"] = diametr;
            return View(listBushing);
        }

        public IActionResult DetailsView(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var bushing = _servicesManager.Bushings.GetBushingViewById(id);

            var stamp = _dataManager.Stamps.GetStampByBushingId(id);
            ViewData["Name"] = stamp.Name;
            if (bushing == null)
            {
                return NotFound();
            }

            return View(bushing);
        }

        public IActionResult Index()
        {
            return View(_dataManager.Bushings.GetAllBushing());
        }

        // GET: Bushings/DetailsView/5
        public IActionResult Details(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var bushing = _dataManager.Bushings.GetBushingById(id);
            if (bushing == null)
            {
                return NotFound();
            }

            return View(bushing);
        }

        // GET: Bushings/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Name,PressedDiametr,FlangeDiametr,ColumnDiametr,TotalHeight,DepthHeight")] Bushing bushing)
        {
            if (ModelState.IsValid)
            {
                _dataManager.Bushings.SaveBushing(bushing);
                return RedirectToAction(nameof(Index));
            }
            return View(bushing);
        }

        // GET: Bushings/Edit/5
        public IActionResult Edit(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var bushing = _dataManager.Bushings.GetBushingById(id);
            if (bushing == null)
            {
                return NotFound();
            }
            return View(bushing);
        }

     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Name,PressedDiametr,FlangeDiametr,ColumnDiametr,TotalHeight,DepthHeight")] Bushing bushing)
        {
            if (id != bushing.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _dataManager.Bushings.SaveBushing(bushing);
                return RedirectToAction(nameof(Index));
            }
            return View(bushing);
        }

        // GET: Bushings/Delete/5
        public IActionResult Delete(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var bushing = _dataManager.Bushings.GetBushingById(id);
            if (bushing == null)
            {
                return NotFound();
            }

            return View(bushing);
        }

        // POST: Bushings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var bushing = _dataManager.Bushings.GetBushingById(id);
            _dataManager.Bushings.DeleteBushing(bushing);
            return RedirectToAction(nameof(Index));
        }

        
    }
}

DesignStamp/Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataLayer.Data;
using DataLayer.Entities;
using BuissnesLayer;
using DesignStamp.Models;
using Microsoft.AspNetCore.Authorization;

namespace DesignStamp.Controllers
{
    [Authorize]
    public class DetailsController : Controller
    {
        readonly private DataManager _dataManager;
        readonly private ServicesManager _servicesManager;

        public DetailsController(DataManager dataManager)
        {

            _dataManager = dataManager;
            _servicesManager = new ServicesManager(_dataManager);
        }

        // GET: DetailsView
        public IActionResult GetAllDetails(string name)
        {
            List<Detail> details = _dataManager.Details.GetAllDetail();
            if (details.Count() == 0)
                ViewData["Flag"] = 1;
            else
                ViewData["Flag"] = 0;


            List<DetailView> detailViews=new List<DetailView>();
            foreach (var item in details)
            {
                var stamp = _dataManager.Stamps.GetStampByDetailName(item.Name);
                string StampName = stamp?.Name ?? "Нету штампа";
                detailViews.Add(new DetailView { Name = item.Name, StampName = StampName });
            }

            if (name != null)
                detailViews= detailViews.Where(s => s.Name == name).ToList();


            return View(detailViews);
        }

        // GET: DetailsView/DetailsView/5
        public IActionResult Details(string name, string returnUrl)
        {
            ViewData["Url"] = returnUrl;
            if (name == null)
            {
                return NotFound();
            }

            var detail = _dataManager.Details.GetDetailByName(name,true);

            if (detail == null)
            {
                return NotFound();
            }

            return View(detail);
        }


        // POST: DetailsView/Delete/5
       
        public IActionResult Delete(string name, string returnUrl)
        {
            ViewData["Url"] = returnUrl;
            var detail = _dataManager.Details.GetDetailByName(name,true);
            return View(detail);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(string Name)
        {
            var stamp = _dataManager.Stamps.GetStampByDetailName(Name);
            if (stamp != null)
                _dataManager.Stamps.DeleteStamp(stamp.Name);
            var detail = _dataManager.Details.GetDetailByName(Name, true);
            _dataManager.Details.DeleteDetail(detail);
            //return RedirectToAction(nameof(GetAllDetails));

            return View();

        }

        [AcceptVerbs("Get", "Post")]
        public IActionResult CheckDetail (string Name)
        {
            var detail = _dataManager.Details.GetDetailByName(Name);
            if (detail == null)
                return Json(true);
            return Json(false);
        }
    }
}

DesignStamp/Views/Bushings/ChooseBushing.cshtml
@model IEnumerable<DataLayer.Entities.Bushing>

@{
    ViewData["Title"] = "ChooseBushing";
    var groups = ViewData["Drops"] as List<DropVIew>;
    var currentDiametr = (int)ViewData["Current"];
    var text = currentDiametr != 0 ? currentDiametr.ToString() : "Все";
}

<h1>Выберите втулку</h1>
<hr />
<div class="row">
    <h4 div class="col-4">Фильтр по диаметру втулки:</h4>
    <div class="col-4">
        <div class="dropdown mt-2">
            <a class="btn btn-secondary dropdown-toggle"
               asp-action="Index" asp-controller="Product" role="button"
               id="dropdownMenuLink"
               data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                @text
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">

                <a class="dropdown-item"
                   asp-action="ChooseBushing"
                   asp-controller="Bushings"
                   asp-route-oldId="@groups.FirstOrDefault().OldId"
                   asp-route-url="@groups.FirstOrDefault().Url">

                    Все
                </a>

                @foreach (var item in groups)
                {
                    <a class="dropdown-item"
                       asp-action="ChooseBushing"
                       asp-controller="Bushings"
                       asp-route-diametr="@item.Diametr"
                       asp-route-oldId="@item.OldId"
                       asp-route-url="@item.Url">
                        @item.Diametr
                    </a>
                }
            </div>
        </div>
    </div>
</div>
<br />
<table class="table">
    <thead>
        <tr>
            <th>
                №
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PressedDiametr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlangeDiametr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ColumnDiametr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalHeight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepthHeight)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PressedDiametr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FlangeDiametr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ColumnDiametr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalHeight)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepthHeight)
            </td>
            <td>
                <a class="btn btn-secondary" asp-controller="Stamps" asp-action="EditBushing" asp-route-id="@item.Id" asp-route-oldId="@groups.FirstOrDefault().OldId">Выбрать </a>

            </td>
        </tr>
}
    </tbody>
</table>
<div class="form-group offset-md-4 col-md-4 ">
    <a href="@groups.FirstOrDefault().Url" class="btn btn-secondary">
        Назад
    </a>
</div>

DesignStamp/Views/Bushings/Create.cshtml
@model DataLayer.Entities.Bushing

@{
    ViewData["Title"] = "Create";
}

<h1>Создание</h1>

<h4>Втулка</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PressedDiametr" class="control-label"></label>
                <input asp-for="PressedDiametr" class="form-control" />
                <span asp-validation-for="PressedDiametr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlangeDiametr" class="control-label"></label>
                <input asp-for="FlangeDiametr" class="form-control" />
                <span asp-validation-for="FlangeDiametr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ColumnDiametr" class="control-label"></label>
                <input asp-for="ColumnDiametr" class="form-control" />
                <span asp-validation-for="ColumnDiametr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalHeight" class="control-label"></label>
                <input asp-for="TotalHeight" class="form-control" />
                <span asp-validation-for="TotalHeight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepthHeight" class="control-label"></label>
                <input asp-for="DepthHeight" class="form-control" />
                <span asp-validation-for="DepthHeight" class="text-danger"></span>
            </div>
            <div class="row">
                <input type="submit" value="Создать" class="col-md-4 btn btn-secondary" />
                <a class="col-md-5 offset-md-3 btn btn-secondary" asp-action="Index">Назад к списку </a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DesignStamp/Views/Bushings/Delete.cshtml
@model DataLayer.Entities.Bushing

@{
    ViewData["Title"] = "Delete";
}

<h1>Удаление</h1>

<h3>Вы действительно хотите удалить втулку?</h3>
<div>
    <h4>Втулка</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PressedDiametr)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PressedDiametr)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FlangeDiametr)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FlangeDiametr)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ColumnDiametr)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ColumnDiametr)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TotalHeight)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TotalHeight)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DepthHeight)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DepthHeight)
        </dd>
    </dl>
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удаление" class="btn btn-danger" />
        <br />
        <br />
        <a class="btn btn-secondary" asp-action="Index">Назад к списку</a>
    </form>
</div>

DesignStamp/Views/Bushings/Details.cshtml
@model DataLayer.Entities.Bushing

@{
    ViewData["Title"] = "Details";
}

<h1>Просмотр</h1>
<div>
    <h4>Втулка</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PressedDiametr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PressedDiametr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlangeDiametr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlangeDiametr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ColumnDiametr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ColumnDiametr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalHeight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalHeight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepthHeight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepthHeight)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-outline-info" asp-action="Edit" asp-route-id="@Model.Id"><span class="fas fa-edit"></span></a>
    <br />
    <br />
    <a class="btn btn-secondary" asp-action="Index">Назад к списку</a>
</div>

DesignStamp/Views/Bushings/DetailsView.cshtml
@model BushingView

@{
    ViewData["Title"] = "Bushing";
    var name = (string)ViewData["Name"];
}


<h3>Втулка</h3>
<div class=" img-fluid">
    <img src="~/images/Втулка.png" width="550" height="350" />
</div>
<br />
<table class="table table-bordered">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ColumnDiametr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PressedDiametr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlangeDiametr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalHeight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepthHeight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Weight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AmountBushing)
            </th>
            <th></th>

        </tr>
    </thead>
    <tbody>

        <tr>

            <td>
                @Html.DisplayFor(modelItem => modelItem.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.ColumnDiametr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.PressedDiametr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.FlangeDiametr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.TotalHeight)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.DepthHeight)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.Weight)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.AmountBushing)
            </td>
            <td>
                @{ // Получение текущего адреса
                    var request = ViewContext.HttpContext.Request;
                    var returnUrl = request.Path + request.QueryString.ToUriComponent();

                }
                <a class="btn btn-outline-info" asp-controller="Bushings" asp-action="ChooseBushing" asp-route-diametr="@Model.ColumnDiametr" asp-route-oldId="@Model.Id" asp-route-url="@returnUrl"><span class="fas fa-edit"></span></a>

            </td>

        </tr>

    </tbody>
</table>
<div class="row">

    <a class="col-md-4 offset-md-4 btn btn-secondary" asp-controller="Stamps" asp-action="GetStamp" asp-route-stampName="@name"> Вернутся к штампу</a>

</div>

DesignStamp/Views/Bushings/Edit.cshtml
@model DataLayer.Entities.Bushing

@{
    ViewData["Title"] = "Edit";
}

<<h1>Редактирование</h1>

<h4>Втулка</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PressedDiametr" class="control-label"></label>
                <input asp-for="PressedDiametr" class="form-control" />
                <span asp-validation-for="PressedDiametr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlangeDiametr" class="control-label"></label>
                <input asp-for="FlangeDiametr" class="form-control" />
                <span asp-validation-for="FlangeDiametr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ColumnDiametr" class="control-label"></label>
                <input asp-for="ColumnDiametr" class="form-control" />
                <span asp-validation-for="ColumnDiametr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalHeight" class="control-label"></label>
                <input asp-for="TotalHeight" class="form-control" />
                <span asp-validation-for="TotalHeight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepthHeight" class="control-label"></label>
                <input asp-for="DepthHeight" class="form-control" />
                <span asp-validation-for="DepthHeight" class="text-danger"></span>
            </div>
            <div class="row">
                <input type="submit" value="Сохранить" class="col-md-4 btn btn-secondary" />
                <a class="col-md-5 offset-md-3 btn btn-secondary" asp-action="Index">Назад к списку </a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DesignStamp/Views/Bushings/Index.cshtml
@model IEnumerable<DataLayer.Entities.Bushing>

@{
    ViewData["Title"] = "Index";
}

<h1>Втулки</h1>

<p>
    <a class="btn btn-outline-primary" asp-action="Create"><span class="fas fa-folder-plus"></span></a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PressedDiametr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlangeDiametr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ColumnDiametr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalHeight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepthHeight)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PressedDiametr)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FlangeDiametr)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ColumnDiametr)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalHeight)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DepthHeight)
                </td>
                <td class="col-md-3">

                    <a class="btn btn-outline-info" asp-action="Edit" asp-route-id="@item.Id"><span class="fas fa-edit"></span></a>
                    <a class="btn btn-outline-success" asp-action="Details" asp-route-id="@item.Id"><span class="fas fa-info"></span></a>
                    <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.Id"><span class="fas fa-trash-alt"></span></a>

                </td>
            </tr>
        }
    </tbody>
</table>
<a class="col-md-3 offset-md-4 btn btn-secondary" asp-controller="Admin">
    Назад к администрированию
</a>