DesignStamp/Models/DetailView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DesignStamp.Models
{
    public class DetailView
    {

        [Display(Name = "№ детали")]
        public string Name { get; set; }
        [Display(Name = "№ штампа")]
        public string StampName { get; set; }

    }
}

DesignStamp/Models/HolderView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DesignStamp.Models
{
    public class HolderView
    {
        [Display(Name = "№ державки")]
        public string Name { get; set; }
        [Display(Name = "Длина (мм)")]
        public double Length { get; set; }
        [Display(Name = "Ширина(мм)")]
        public double Width { get; set; }
        [Display(Name = "Высота (мм)")]
        public double TotalHieght { get; set; }
        [Display(Name = "Толщина верха (мм)")]
        public double BodyHieght { get; set; }
        [Display(Name = "Масса (кг)")]
        public double Weight { get; set; }
        public string StampName { get; set; }


    }
}

DesignStamp/Areas/Identity/Pages/Account/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataLayer.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace DesignStamp.Areas.Identity.Pages.Account
{
    public class EditModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<EditModel> _logger;

        public EditModel(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            ILogger<EditModel> logger)

        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;

        }
        [BindProperty]
        public ApplicationUser User1 { get; set; }
        public async Task<IActionResult> OnGetAsync( string name)
        {
            //ReturnUrl = returnUrl;

            User1 =await _userManager.FindByNameAsync(name);
            return Page();
            
        }
    }
}

DesignStamp/Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataLayer.Data;
using DataLayer.Entities;
using BuissnesLayer;
using DesignStamp.Models;
using Microsoft.AspNetCore.Authorization;

namespace DesignStamp.Controllers
{
    [Authorize]
    public class DetailsController : Controller
    {
        readonly private DataManager _dataManager;
        readonly private ServicesManager _servicesManager;

        public DetailsController(DataManager dataManager)
        {

            _dataManager = dataManager;
            _servicesManager = new ServicesManager(_dataManager);
        }

        // GET: DetailsView
        public IActionResult GetAllDetails(string name)
        {
            List<Detail> details = _dataManager.Details.GetAllDetail();
            if (details.Count() == 0)
                ViewData["Flag"] = 1;
            else
                ViewData["Flag"] = 0;


            List<DetailView> detailViews=new List<DetailView>();
            foreach (var item in details)
            {
                var stamp = _dataManager.Stamps.GetStampByDetailName(item.Name);
                string StampName = stamp?.Name ?? "Нету штампа";
                detailViews.Add(new DetailView { Name = item.Name, StampName = StampName });
            }

            if (name != null)
                detailViews= detailViews.Where(s => s.Name == name).ToList();


            return View(detailViews);
        }

        // GET: DetailsView/DetailsView/5
        public IActionResult Details(string name, string returnUrl)
        {
            ViewData["Url"] = returnUrl;
            if (name == null)
            {
                return NotFound();
            }

            var detail = _dataManager.Details.GetDetailByName(name,true);

            if (detail == null)
            {
                return NotFound();
            }

            return View(detail);
        }


        // POST: DetailsView/Delete/5
       
        public IActionResult Delete(string name, string returnUrl)
        {
            ViewData["Url"] = returnUrl;
            var detail = _dataManager.Details.GetDetailByName(name,true);
            return View(detail);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(string Name)
        {
            var stamp = _dataManager.Stamps.GetStampByDetailName(Name);
            if (stamp != null)
                _dataManager.Stamps.DeleteStamp(stamp.Name);
            var detail = _dataManager.Details.GetDetailByName(Name, true);
            _dataManager.Details.DeleteDetail(detail);
            //return RedirectToAction(nameof(GetAllDetails));

            return View();

        }

        [AcceptVerbs("Get", "Post")]
        public IActionResult CheckDetail (string Name)
        {
            var detail = _dataManager.Details.GetDetailByName(Name);
            if (detail == null)
                return Json(true);
            return Json(false);
        }
    }
}

DesignStamp/Controllers/HoldersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataLayer.Data;
using DataLayer.Entities;
using BuissnesLayer;
using Microsoft.AspNetCore.Authorization;

namespace DesignStamp.Controllers
{
    [Authorize]
    public class HoldersController : Controller
    {
       readonly private DataManager _dataManager;
        readonly private ServicesManager _servicesManager;

        public HoldersController(DataManager dataManager)
        {

            _dataManager = dataManager;
            _servicesManager = new ServicesManager(_dataManager);
        }


        public IActionResult Details(string stampName)
        {
            if (stampName == null)
            {
                return NotFound();
            }

            var holder = _servicesManager.Holders.GetHolderViewByStampName(stampName);

            if (holder == null)
            {
                return NotFound();
            }

            return View(holder);
        }


        public IActionResult Edit(string stampName, string returnUrl)
        {
            ViewData["Url"] = returnUrl;
            if (stampName == null)
            {
                return NotFound();
            }

            var holder = _dataManager.Holders.GetHolderByStampName(stampName);
            if (holder == null)
            {
                return NotFound();
            }
            
            return View(holder);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(string name, [Bind("Name,Length,Width,TotalHieght,BodyHieght,StampName,")] Holder holder)
        {
            if (name != holder.Name)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                _dataManager.Holders.SaveHolder(holder);

            }
            else
            {
                return RedirectToAction(nameof(Details), new { @stampName = holder.StampName });
            }



            return RedirectToAction(nameof(Details), new { @stampName = holder.StampName });
        }
    }
}

DesignStamp/Views/Holders/Details.cshtml
@model HolderView


@{
    ViewData["Title"] = "Holder";
}

<h3>Державка</h3>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Length)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Width)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalHieght)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BodyHieght)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Weight)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        <tr>
            <td>
                @Html.DisplayFor(modelItem => modelItem.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.Length)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.Width)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.TotalHieght)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.BodyHieght)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.Weight)
            </td>
            <td>
                @{ // Получение текущего адреса
                    var request = ViewContext.HttpContext.Request;
                    var returnUrl = request.Path + request.QueryString.ToUriComponent();

                }
                <a class="btn btn-outline-info" asp-controller="Holders" asp-action="Edit" asp-route-stampName="@Model.StampName" asp-route-returnUrl="@returnUrl"><span class="fas fa-edit"></span></a>

            </td>
        </tr>

    </tbody>
</table>

<div class="row">

    <a class="col-md-4 offset-md-4 btn btn-secondary" asp-controller="Stamps" asp-action="GetStamp" asp-route-stampName="@Model.StampName"> Вернутся к штампу</a>

</div>

DesignStamp/Views/Holders/Edit.cshtml
@model DataLayer.Entities.Holder

@{
    ViewData["Title"] = "Edit";
    string url = (string)ViewData["Url"] ?? "#";
}

<h2>Редактирование</h2>

<h4>Державка</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Name" />
            <div class="form-group">
                <label asp-for="Length" class="control-label"></label>
                <input asp-for="Length" class="form-control" />
                <span asp-validation-for="Length" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Width" class="control-label"></label>
                <input asp-for="Width" class="form-control" />
                <span asp-validation-for="Width" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalHieght" class="control-label"></label>
                <input asp-for="TotalHieght" class="form-control" />
                <span asp-validation-for="TotalHieght" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BodyHieght" class="control-label"></label>
                <input asp-for="BodyHieght" class="form-control" />
                <span asp-validation-for="BodyHieght" class="text-danger"></span>
            </div>
            <input asp-for="StampName" type="hidden" />
            <div class="form-row">
                <div class="form-group col-md-4 " >
                    <input type="submit" value="Сохранить" class="btn btn-secondary" />
                </div>
                <div class="form-group offset-md-4 col-md-4 ">
                    <a href="@url" class="btn btn-secondary">
                        Назад
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}