DesignStamp/Models/BottomPlateView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DesignStamp.Models
{
    public class BottomPlateView
    {
        [Display(Name = "№ плиты")]
        public string Name { get; set; }
        [Display(Name = "Длина (мм)")]
        public double TotalLength { get; set; }
        [Display(Name = "Длина отлива (мм)")]
        public double СastLength { get; set; }
        [Display(Name = "Ширина отлива (мм)")]
        public double СastWidth { get; set; }
        [Display(Name = "Высота отлива (мм)")]
        public double СastHeight { get; set; }
        [Display(Name = "Ширина (мм)")]
        public double TotalWidth { get; set; }
        [Display(Name = "Ширина полки (мм)")]
        public double SfelfWidth { get; set; }
        [Display(Name = "Высота полки (мм)")]
        public double SfelfHeight { get; set; }
        [Display(Name = "Высота (мм)")]
        public double Hieght { get; set; }
        [Display(Name = "Масса (кг)")]
        public double Weight { get; set; }

        public string StampName { get; set; }
    }
}

DesignStamp/Models/DetailView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DesignStamp.Models
{
    public class DetailView
    {

        [Display(Name = "№ детали")]
        public string Name { get; set; }
        [Display(Name = "№ штампа")]
        public string StampName { get; set; }

    }
}

DesignStamp/Areas/Identity/Pages/Account/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataLayer.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace DesignStamp.Areas.Identity.Pages.Account
{
    public class EditModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<EditModel> _logger;

        public EditModel(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            ILogger<EditModel> logger)

        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;

        }
        [BindProperty]
        public ApplicationUser User1 { get; set; }
        public async Task<IActionResult> OnGetAsync( string name)
        {
            //ReturnUrl = returnUrl;

            User1 =await _userManager.FindByNameAsync(name);
            return Page();
            
        }
    }
}

DesignStamp/Controllers/BottomPlatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataLayer.Data;
using DataLayer.Entities;
using BuissnesLayer;
using Microsoft.AspNetCore.Authorization;

namespace DesignStamp.Controllers
{
    [Authorize]
    public class BottomPlatesController : Controller
    {
        readonly private DataManager _dataManager;
        readonly private ServicesManager _servicesManager;

        public BottomPlatesController(DataManager dataManager)
        {

            _dataManager = dataManager;
            _servicesManager = new ServicesManager(_dataManager);
        }


        public IActionResult Details(string stampName)
        {
            if (stampName == null)
            {
                return NotFound();
            }

            var bottomPlate = _servicesManager.BottomPlates.GetBottomPlateViewByStampName(stampName);

            if (bottomPlate == null)
            {
                return NotFound();
            }

            return View(bottomPlate);
        }

        public IActionResult Edit(string stampName, string returnUrl)
        {
            ViewData["Url"] = returnUrl;
            if (stampName == null)
            {
                return NotFound();
            }

            var bottomPlate = _dataManager.BottomPlates.GetBottomPlateByStampName(stampName);
            if (bottomPlate == null)
            {
                return NotFound();
            }

            return View(bottomPlate);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(string name, [Bind("Name,Length,Width,Hieght,StampName")] BottomPlate bottomPlate)
        {

            if (name != bottomPlate.Name)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                _dataManager.BottomPlates.SaveBottomPlate(bottomPlate);

            }
            else
            {
                return RedirectToAction(nameof(Details), new { @stampName = bottomPlate.StampName });
            }



            return RedirectToAction(nameof(Details), new { @stampName = bottomPlate.StampName });
        }

      
    }
}

DesignStamp/Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataLayer.Data;
using DataLayer.Entities;
using BuissnesLayer;
using DesignStamp.Models;
using Microsoft.AspNetCore.Authorization;

namespace DesignStamp.Controllers
{
    [Authorize]
    public class DetailsController : Controller
    {
        readonly private DataManager _dataManager;
        readonly private ServicesManager _servicesManager;

        public DetailsController(DataManager dataManager)
        {

            _dataManager = dataManager;
            _servicesManager = new ServicesManager(_dataManager);
        }

        // GET: DetailsView
        public IActionResult GetAllDetails(string name)
        {
            List<Detail> details = _dataManager.Details.GetAllDetail();
            if (details.Count() == 0)
                ViewData["Flag"] = 1;
            else
                ViewData["Flag"] = 0;


            List<DetailView> detailViews=new List<DetailView>();
            foreach (var item in details)
            {
                var stamp = _dataManager.Stamps.GetStampByDetailName(item.Name);
                string StampName = stamp?.Name ?? "Нету штампа";
                detailViews.Add(new DetailView { Name = item.Name, StampName = StampName });
            }

            if (name != null)
                detailViews= detailViews.Where(s => s.Name == name).ToList();


            return View(detailViews);
        }

        // GET: DetailsView/DetailsView/5
        public IActionResult Details(string name, string returnUrl)
        {
            ViewData["Url"] = returnUrl;
            if (name == null)
            {
                return NotFound();
            }

            var detail = _dataManager.Details.GetDetailByName(name,true);

            if (detail == null)
            {
                return NotFound();
            }

            return View(detail);
        }


        // POST: DetailsView/Delete/5
       
        public IActionResult Delete(string name, string returnUrl)
        {
            ViewData["Url"] = returnUrl;
            var detail = _dataManager.Details.GetDetailByName(name,true);
            return View(detail);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(string Name)
        {
            var stamp = _dataManager.Stamps.GetStampByDetailName(Name);
            if (stamp != null)
                _dataManager.Stamps.DeleteStamp(stamp.Name);
            var detail = _dataManager.Details.GetDetailByName(Name, true);
            _dataManager.Details.DeleteDetail(detail);
            //return RedirectToAction(nameof(GetAllDetails));

            return View();

        }

        [AcceptVerbs("Get", "Post")]
        public IActionResult CheckDetail (string Name)
        {
            var detail = _dataManager.Details.GetDetailByName(Name);
            if (detail == null)
                return Json(true);
            return Json(false);
        }
    }
}

DesignStamp/Views/BottomPlates/Details.cshtml
@model BottomPlateView
<h3>Нижняя плита</h3>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalLength)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalWidth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hieght)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SfelfHeight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SfelfWidth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.СastLength)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.СastWidth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.СastHeight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Weight)
            </th>
        </tr>
    </thead>
    <tbody>


        <tr>
            <td>
                @Html.DisplayFor(model => model.Name)
            </td>
            <td>
                @Html.DisplayFor(model => model.TotalLength)
            </td>
            <td>
                @Html.DisplayFor(model => model.TotalWidth)
            </td>
            <td>
                @Html.DisplayFor(model => model.Hieght)
            </td>
            <td>
                @Html.DisplayFor(model => model.SfelfHeight)
            </td>
            <td>
                @Html.DisplayFor(model => model.SfelfWidth)
            </td>
            <td>
                @Html.DisplayFor(model => model.СastLength)
            </td>
            <td>
                @Html.DisplayFor(model => model.СastWidth)
            </td>
            <td>
                @Html.DisplayFor(model => model.СastHeight)
            </td>
            <td>
                @Html.DisplayFor(model => model.Weight)
            </td>
            <td>

                @{ // Получение текущего адреса
                    var request = ViewContext.HttpContext.Request;
                    var returnUrl = request.Path + request.QueryString.ToUriComponent();

                }

                <a class="btn btn-outline-info" asp-controller="BottomPlates" asp-action="Edit" asp-route-stampName="@Model.StampName" asp-route-returnUrl="@returnUrl"><span class="fas fa-edit"></span></a>
            </td>
        </tr>

    </tbody>
</table>
<div class="row">

    <a class="col-md-4 offset-md-4 btn btn-secondary" asp-controller="Stamps" asp-action="GetStamp" asp-route-stampName="@Model.StampName"> Вернутся к штампу</a>

</div>

DesignStamp/Views/BottomPlates/Edit.cshtml
@model DataLayer.Entities.BottomPlate

@{
    ViewData["Title"] = "Edit";
    string url = (string)ViewData["Url"] ?? "#";
}


<h2>Редактирование</h2>

<h4>Нижняя плита</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalLength" class="control-label"></label>
                <input asp-for="TotalLength" class="form-control" />
                <span asp-validation-for="TotalLength" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalWidth" class="control-label"></label>
                <input asp-for="TotalWidth" class="form-control" />
                <span asp-validation-for="TotalWidth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hieght" class="control-label"></label>
                <input asp-for="Hieght" class="form-control" />
                <span asp-validation-for="Hieght" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SfelfWidth" class="control-label"></label>
                <input asp-for="SfelfWidth" class="form-control" />
                <span asp-validation-for="SfelfWidth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SfelfHeight" class="control-label"></label>
                <input asp-for="SfelfHeight" class="form-control" />
                <span asp-validation-for="SfelfHeight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="СastLength" class="control-label"></label>
                <input asp-for="СastLength" class="form-control" />
                <span asp-validation-for="СastLength" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="СastWidth" class="control-label"></label>
                <input asp-for="СastWidth" class="form-control" />
                <span asp-validation-for="СastWidth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="СastHeight" class="control-label"></label>
                <input asp-for="СastHeight" class="form-control" />
                <span asp-validation-for="СastHeight" class="text-danger"></span>
            </div>

           
            <input type="hidden" asp-for="StampName" />
            <div class="form-row">
                <div class="form-group col-md-4">
                    <input type="submit" value="Сохранить" class="btn btn-secondary" />
                </div>
                <div class="form-group offset-md-4 col-md-4 ">
                    <a href="@url" class="btn btn-secondary">
                        Назад
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}